version: '3.8'
services:
  mongo:
    image: mongo:8.0
    volumes: 
     - mongo_data:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z   
    volumes:
      - minio_data:/data 
    restart: always
    ports:
      - 9000:9000   
      - 9001:9001     
    environment:
      MINIO_ROOT_USER: minioadmin        # Change to a secure user in production
      MINIO_ROOT_PASSWORD: minioadmin    # Change to a secure password
    command: server /data --console-address ":9001"   


volumes:
  mongo_data:
  minio_data:
